### ISSUE TITLE
rack 3.0 support

### ISSUE THREAD

**Issue by metapsj** [cyx/shield#25]
will shield support rack 3.0?

here some of the changes that effect shield.

- Response header keys can no longer include uppercase characters.
- Rack::Headers added to support lower-case header keys.

i've included links to rack 3.0's change log and upgrade guide as a convenience.

change log
https://github.com/rack/rack/blob/3.0.0/CHANGELOG.md

upgrade guide
https://github.com/rack/rack/blob/3.0.0/UPGRADE-GUIDE.md

**Comment by soveran** [comment]
Hey @metapsj, I've just pushed version 3 which supports Rack 3.

Thanks a lot for the heads up!
